### PR TITLE
Category testing - model and features

### PR DESCRIPTION
**Pull request by steviekaye**
Added simple model and feature testing for the categories page. This involved adding the RecordTagHelper gem as the div_for functionality is no longer core to Rails/ActionView.

### CODE REVIEW

**Comment by kfrn** [comment]
Unfortunately 11 of the 16 tests are failing for me, with the error `Validation failed: Name has already been taken`.

I'd advise you to look into the FactoryBot `sequence`, in order to ensure unique names. And then in places where you don't want unique names, create the instances manually and overriding the name, e.g. `FactoryBot.create(:category, name: 'A name I will reuse')`.

**Comment by kfrn** [comment]
Re: `RecordTagHelper` and `div_for`, I don't think you necessarily need it. Though, setting it inline (e.g. `each_with_index` + `<div class="buttons" id=<%= "category_#{idx}" %>>` is a bit ugly. I think the best option could be 
```ruby
<% @categories.each_with_index do |category, idx| %>
   <%= content_tag :div, class: 'buttons', id: "category_#{idx}" do %>
      [...]
   <% end %>
<% end %>
```

Also, it doesn't have to be in this PR, but in the near future could you please go through and fix the indentation in all your views. Some are in good shape, but there's also a lot of misalignment (e.g., in this PR, the categories index), and it's not very readable. Sometimes empty lines may help readability, too, though that is more a matter of taste. :-)  
I don't think Atom Beautify is great with `erb` files, you may be better turning it off for `erb` and manually setting things :(

**Comment by steviekaye** [comment]
> Re: `RecordTagHelper` and `div_for`, I don't think you necessarily need it. Though, setting it inline (e.g. `each_with_index` + `<div class="buttons" id=<%= "category_#{idx}" %>>` is a bit ugly. I think the best option could be
> 
> ```ruby
> <% @categories.each_with_index do |category, idx| %>
>    <%= content_tag :div, class: 'buttons', id: "category_#{idx}" do %>
>       [...]
>    <% end %>
> <% end %>
> ```
> 
I'll think about using that formatting instead of div_for, but I'd like to put it aside for the moment while things are "working" and return to it later.

> Also, it doesn't have to be in this PR, but in the near future could you please go through and fix the indentation in all your views. Some are in good shape, but there's also a lot of misalignment (e.g., in this PR, the categories index), and it's not very readable. Sometimes empty lines may help readability, too, though that is more a matter of taste. :-)

> I don't think Atom Beautify is great with `erb` files, you may be better turning it off for `erb` and manually setting things :(

I tried turning it off under Atom Beautify settings under Ruby, both disabling it plus turning off the "beautify on save" option, but it kept doing it :( I definitely wouldn't choose to format e.g. that category index.html.erb like that!
Wait! Turns out I was looking under both HTML and Ruby beautification options, not realising there was a dedicated ERB section. After looking up similar problems, I've installed a different beautifier, (HTML Beautifier instead of Pretty Diff) which seems to be doing better with the indentation?

**Comment by steviekaye** [comment]
> Tests passing now! Though, since you've had to add the `after` block in each feature spec file, that suggests to me that you should change your config instead, e.g.
> 
> ```ruby
> config.after(:all) do
>     DatabaseCleaner.clean_with(:truncation)
> end
> ```

Since I'm not running it after e.g. model tests, I'd rather keep each after(:all) paired with the times I'm using before(:all) - seems more symmetrical that way.

**Comment by kfrn** [comment]
Looking pretty good, just a few things:

1. **Remove `div_for` and the library it's from**
Instead,
```ruby
<% @categories.each_with_index do |category, idx| %>
   <%= content_tag :div, class: 'buttons', id: "category_#{idx + 1}" do %>
      [...]
   <% end %>
<% end %>
```

2. **Typo: sucessfully**
There are still a few you missed

3. **Tests**
The test syntax I was suggesting would simply look like this:
```ruby
context 'when the subcategory name already exists within that category' do
    it 'is not created' do
      expect do
        within('div#category_1') do
          fill_in 'subcategory_name', with: 'ExistingSubCategory'
          click_on 'create_subcategory'
        end
      end.to change(Subcategory.all, :count).by(0)
    end
  end
```
For simple scenarios I wouldn't bother, but since the scenarios are conditional, I think it's just a bit easier to read, compare:
subcategories

4. **Error handling**
Let's not worry about it right now - but currently, if you try to create a subcategory that already exists, it correctly fails, but there's no error displayed. Let's make a backlog task for this.

**Pull request merged**
